name: Version Bump and Create Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  version_bump:
    name: Version Bump and PR Creation
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if it's upstream and main branch
        run: |
          if [ "$GITHUB_REPOSITORY" != "flockx-official/fetchai" ]; then
            echo "Not the upstream repository. Skipping version bump."
            exit 0
          fi
          if [ "${{ github.event.pull_request.base.ref }}" != "main" ]; then
            echo "Not merging into main. Skipping version bump."
            exit 0
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel bump2version twine

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 4: Bump the version (patch version by default, can be customized)
      - name: Bump version
        id: bump_version
        run: |
          source venv/bin/activate
          bump2version patch

      # Step 5: Capture the new version and set it as an output
      - name: Get the new version
        id: get_version
        run: |
          source venv/bin/activate
          new_version=$(bump2version --list patch | grep new_version= | sed -r s,"^.*=",,)
          echo "New version is $new_version"
          echo "::set-output name=new_version::$new_version"
        shell: bash

      # Step 6: Create a new branch for the version bump
      - name: Create new branch for version bump
        run: |
          git checkout -b version-bump-v${{ steps.get_version.outputs.new_version }}
          git commit -am "Version bump to v${{ steps.get_version.outputs.new_version }}"

      # Step 7: Push the new branch
      - name: Push new branch
        run: |
          git push origin version-bump-v${{ steps.get_version.outputs.new_version }}

      # Step 8: Create a pull request for the version bump
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Version bump to v${{ steps.get_version.outputs.new_version }}"
          branch: version-bump-v${{ steps.get_version.outputs.new_version }}
          title: "Version bump to v${{ steps.get_version.outputs.new_version }}"
          body: "This pull request bumps the version to v${{ steps.get_version.outputs.new_version }}."
          base: main